from typing import TypedDict, NotRequired


class ResearchState(TypedDict):
    topic: str                    # Input: chủ đề cần viết
    category: str                 # nguon-goc | rang-xay | pha-che | nghien-cuu
    search_queries: NotRequired[list[str]]  # Generated by query_gen_node (EN + JA)
    search_results: list[dict]    # Output của research_node
    extracted_docs: list[dict]    # Output của extract_node
    article_outline: NotRequired[dict]       # Dàn ý do outline_node tạo
    article_images: NotRequired[list[dict]]  # Ảnh thực tế từ Unsplash (image_fetch_node)
    draft_post: str               # Bản nháp từ draft_node
    draft_post_original: NotRequired[str]  # Bản nháp gốc (trước rewrite), title có "[DRAFT] "
    review_feedback: NotRequired[str]      # JSON string từ review_node
    user_materials: NotRequired[list[dict]]    # Materials từ user
    research_sources: NotRequired[list[str]]   # Nguồn research được bật: arxiv, openalex, web, youtube
