from typing import TypedDict, NotRequired


class ResearchState(TypedDict):
    topic: str                    # Input: chủ đề cần viết
    category: str                 # nguon-goc | rang-xay | pha-che | nghien-cuu
    search_queries: NotRequired[list[str]]  # Generated by query_gen_node (EN + JA)
    search_results: list[dict]    # Output của research_node
    extracted_docs: list[dict]    # Output của extract_node
    article_outline: NotRequired[dict]       # Dàn ý do outline_node tạo
    article_images: NotRequired[list[dict]]  # Ảnh thực tế từ Unsplash (image_fetch_node)
    draft_post: str               # Bản nháp từ draft_node
    review_feedback: str          # Feedback từ review_node
    review_score: float           # Điểm 0-10 từ review_node
    review_passed: bool           # True nếu score >= 8.0
    revision_count: int           # Số vòng lặp đã thực hiện (tăng trong review_node)
